project: mutation-prediction
name: epistatic

data:
  dataset: megascale
  mut_types: [double]
  splits: [train, val]

data_loc:
  megascale_csv: data/raw/megascale/csv/Megascale-D-full.csv

training:
  num_workers: 4
  output_dir: checkpoints/model
  learn_rate: 0.00001
  epochs: 100
  lr_schedule: true
  batch_size: 128
  shuffle: true

model:
  mutant_embedding: true # indicates whether you should subtract embedding of mutant from WT
  num_final_layers: 2 # number of proteinmpnn layers to extract from
  freeze_weights: true # indicates whether proteinmpnn weights are frozen
  load_pretrained: true # indicates whether to load a frozen proteinmpnn
  proteinmpnn_dropout: 0.0
  dropout: 0.1 # dropout for the model
